-- Run once to create the submissions table
CREATE TABLE IF NOT EXISTS MARKETING.PLAYGROUND.SUPERHERO_CREATOR_CONF_SUBMISSIONS (
    SUBMISSION_ID          VARCHAR        NOT NULL PRIMARY KEY,
    SUBMITTED_AT           VARCHAR,
    -- Contact
    FIRST_NAME             VARCHAR,
    LAST_NAME              VARCHAR,
    EMAIL                  VARCHAR,
    JOB_TITLE              VARCHAR,
    COMPANY                VARCHAR,
    COUNTRY                VARCHAR,
    LINKEDIN_URL           VARCHAR,
    GITHUB_USERNAME        VARCHAR,
    TWITTER_HANDLE         VARCHAR,
    WEBSITE_URL            VARCHAR,
    -- Community identity
    COMMUNITY_IDENTITY     VARCHAR,
    SUPERHERO_PROFILE_URL  VARCHAR,
    STREAMLIT_CREATOR_PROFILE_URL VARCHAR,
    SNOWFLAKE_COMMUNITY_USERNAME  VARCHAR,
    YEARS_SNOWFLAKE        VARCHAR,
    -- Audience reach
    LINKEDIN_FOLLOWERS     INTEGER DEFAULT 0,
    TWITTER_FOLLOWERS      INTEGER DEFAULT 0,
    YOUTUBE_SUBSCRIBERS    INTEGER DEFAULT 0,
    NEWSLETTER_SUBSCRIBERS INTEGER DEFAULT 0,
    GITHUB_STARS           INTEGER DEFAULT 0,
    OTHER_REACH_NOTES      VARCHAR,
    -- Past involvement
    PAST_TALKS_COUNT       VARCHAR,
    PAST_CONTENT_SUMMARY   VARCHAR,
    NOTABLE_PROJECTS       VARCHAR,
    -- Conference
    CONFERENCE_NAME        VARCHAR,
    CONFERENCE_WEBSITE     VARCHAR,
    CONFERENCE_TYPE        VARCHAR,
    CONFERENCE_START_DATE  VARCHAR,
    CONFERENCE_END_DATE    VARCHAR,
    CONFERENCE_CITY        VARCHAR,
    CONFERENCE_COUNTRY     VARCHAR,
    CONFERENCE_FORMAT      VARCHAR,
    -- Talk
    TALK_TITLE             VARCHAR,
    SESSION_TYPE           VARCHAR,
    TALK_ABSTRACT          VARCHAR,
    SNOWFLAKE_TOPICS       VARIANT,
    ACCEPTANCE_STATUS      VARCHAR,
    -- Support
    SUPPORT_TYPES          VARIANT,
    ESTIMATED_COST_USD     FLOAT DEFAULT 0,
    TRAVELING_FROM         VARCHAR,
    ADDITIONAL_NOTES       VARCHAR
);
